### ISSUE TITLE
potential WG note explaining what we did

### ISSUE THREAD

**Issue by pfps** [w3c/rdf-star-wg#124]
During the Semantic TF meeting on 28 June there was a suggestion that the WG create a note with explanatory material.   

This material should not go in Concepts.

**Comment by pfps** [comment]
This should probably be part of the "What's new" deliverable.

**Comment by pfps** [comment]
There is already https://w3c.github.io/rdf-new/spec/

**Comment by pchampin** [comment]
This was discussed during the [rdf-star meeting on 31 October 2024](https://www.w3.org/2024/10/31-rdf-star-minutes.html#04a3).

<details><summary><i>View the transcript</i></summary>

<h3>potential WG note explaining what we did <a href="https://github.com/w3c/rdf-star-wg/issues/124" rel="noopener noreferrer">1</a></h3>
<p><cite>pfps:</cite> most WG do something along this line<br>
<span>… we haven't yet decided to do it but I think it would be a good idea</span><br>
<span>… I just noticed there is a "what's new" deliverable</span></p>
<p><cite>&lt;AndyS&gt;</cite> 4 possible places New, primer, concepts, note - depends on the ambition - e.g. patterns and anti-patterns</p>
<p><cite>&lt;pfps&gt;</cite> <a href="https://w3c.github.io/rdf-new/spec/" rel="noopener noreferrer">https://<wbr>w3c.github.io/<wbr>rdf-new/<wbr>spec/</a></p>
<p><cite>pfps:</cite> In fact there is one (see URL above)<br>
<span>… we'll do it</span></p>
<p><cite>ktk:</cite> we still have to see who can work on this</p>

<hr /></details>
