### ISSUE TITLE
Convert SPARQL specs to ReSpec

### ISSUE THREAD

**Issue by afs** [w3c/rdf-star-wg#3]
This issue is for discussion and tracking work to convert SPARQL 1.1 specifications to [ReSpec](https://respec.org/) (or decide not to convert a spec).

They are all mentioned in the [RDF-star charter](https://www.w3.org/2022/08/rdf-star-wg-charter/).

- [x] [Overview](http://www.w3.org/TR/sparql11-overview)
- [x] [Query](http://www.w3.org/TR/sparql11-query)
- [x] [Update](http://www.w3.org/TR/sparql11-update)
- [x] [Service Description](http://www.w3.org/TR/sparql11-service-description)
- [x] [Federated Query](http://www.w3.org/TR/sparql11-federated-query)
- [x] [Query Results JSON Format](http://www.w3.org/TR/sparql11-results-json)
- [x] [Query Results CSV and TSV Formats](http://www.w3.org/TR/sparql11-results-csv-tsv)
- [x] [Query Results XML Format (Second Edition)](http://www.w3.org/TR/rdf-sparql-XMLres)
- [x] [Entailment Regimes](http://www.w3.org/TR/sparql11-entailment)
- [x] [Protocol](http://www.w3.org/TR/sparql11-protocol)
- [x] [Graph Store HTTP Protocol](http://www.w3.org/TR/sparql11-http-rdf-update)

Many of the specs were written in XML, to produce HTML via a W3C XSLT pipeline.

This means that while the HTML is "not pretty", it is quite regular.
Using [HTML tidy](https://www.html-tidy.org/) produces HTML that is better for editing.

Hopefully, a basic bulk conversion can be done by automation.

**Comment by afs** [comment]
I've manged to extract the contents of "query" to generate a ReSpec document. The contents are converted by sccipt.

This at least shows that conversion is possible.

_Unfinished_ work-in-progress:
https://afs.github.io/sparql-respec/query/doc.html

**Comment by afs** [comment]
**Layout**

Each document SPARQL document repo is following the style elsewhere with:

* No `/index.html`
* Content in `spec/index.html`

There is also `input/` which holds fixed up HTML original of the SPARQL 1.1 document.

**Process for initial HTML**
1. Save the original HTML from SPARQL 1.1. The originals are saved as complete pages (with `FOO_files/` subdirectory) from the REC page, not taken from the repo because there is an XSLT transform to produce the REC HTML.
2. Run through `HTML tidy` to get vaguely readable layout which is consistently formatted for script processing.
3. Fixup the HTML if necessary (there are a few HTML errors)
4. Update two docs (`sparql-xml-results`, `sparql-graph-store-protocol`) don't conform to the layout of the other documents.

**Comment by afs** [comment]
Mistakes in bulk conversion:

The editors draft link is to short name, not the repo name: `sparql12-`  not `sparql-`.

**Comment by pchampin** [comment]
I believe this can be closed, right? :)

**Comment by afs** [comment]
Yes!
