### ISSUE TITLE
chairs to contact I18N group to start discussion

### ISSUE THREAD

**Issue by pchampin** [w3c/rdf-star-wg#31]
(ghurlbot failed to create [this action](https://www.w3.org/2023/02/23-rdf-star-minutes.html#a01) during the 2023-02-23 meeting)

**Comment by rdfguy** [comment]
And it is already completed.

Ora


From: Pierre-Antoine Champin ***@***.***>
Reply-To: w3c/rdf-star-wg ***@***.***>
Date: Wednesday, March 15, 2023 at 9:19 AM
To: w3c/rdf-star-wg ***@***.***>
Cc: "Lassila, Ora" ***@***.***>, Assign ***@***.***>
Subject: [w3c/rdf-star-wg] chairs to contact I18N group to start discussion (Issue #31)


(ghurlbot failed to create this action<https://www.w3.org/2023/02/23-rdf-star-minutes.html#a01> during the 2023-02-23 meeting)
