### ISSUE TITLE
consider moving wiki work from GitHub-hosted to W3-hosted

### ISSUE THREAD

**Issue by TallTed** [w3c/rdf-star-wg#38]
Please forgive the built-in bias of this issue.

GitHub wiki is tragically under-featured. Major lacks that I run into start with these:

* There is no "alert" mechanism associated with GitHub wiki pages, so the only way to discover that a wiki page has been updated is to visit the page. 
* There is no comparison across page versions, so you cannot see what changes have been made, for instance, since your last visit, nor since the last edit you know you saw, nor between this version and the previous, etc.

I have not yet encountered a feature that GitHub Wiki has that other Wikis lack.

Historically, all W3 WGs (and various other W3 entities) were automatically (whether by human or bot, I don't know) assigned a homepage within the overarching [W3 Wiki](https://www.w3.org/wiki/Main_Page), which is a fully-fledged wiki, which *does* provide all the things that the GitHub wiki fails to provide.

I strongly advise and request that we consider moving the RDF-star wiki work from the [GitHub wiki](https://github.com/w3c/rdf-star-wg/wiki) to the [W3 wiki](https://www.w3.org/wiki/Main_Page).

**Comment by gkellogg** [comment]
I think the W3 Wiki is good for longer-term pages, such as "Cool URIs". While the purpose of our local Wiki entries is more for operational WG topics (although, some of them may become useful to retain in the long term).

Alternatively, we could do as I did for the [Text direction](https://github.com/w3c/rdf-star-wg/blob/main/docs/text-direction.md) discussion, and use Markdown files in the repo. This would use the normal PR process for creating an updating; the Wik turns into an index.

**Comment by TallTed** [comment]
First, note that _Cool URIs_ isn't in the W3 Wiki; it's an [Interest Group NOTE](https://www.w3.org/TR/cooluris/)) from the [Semantic Web Education and Outreach (SWEO) Interest Group](http://www.w3.org/2001/sw/sweo/).

The W3 Wiki contains both longer-term pages and shorter-term pages. See, for semi-random examples, the [Linked Data Platform Working Group](https://www.w3.org/2012/ldp/wiki/Main_Page), the [Government Linked Data (GLD) Working Group](https://www.w3.org/2011/gld/wiki/Main_Page), the [CSV on the Web Working Group](https://www.w3.org/2013/csvw/wiki/Main_Page), and, of particular relevance, the [[2011] RDF [1.1] Working Group](https://www.w3.org/2011/rdf-wg/wiki/Main_Page). Also, note that the [Semantic Web Education and Outreach Interest Group](https://www.w3.org/wiki/SweoIG) wiki section includes such shorter-term pages as [SweoIG/Misc/LogoIdeas](https://www.w3.org/wiki/SweoIG/Misc/LogoIdeas)....

That said, I would be fine with Markdown (or HTML or plaintext or whatever makes sense for each) files within the repo. Mostly, I want change notification though I prefer collaboration on, rather than after-the-fact notification of, such changes. I do prefer git-managed documents over wiki pages, and advise and request that changes go through PRs, typically allowing 3–7 days for comment before merging, rather than direct commits (which are analogous to edits to a wiki).

**Comment by gkellogg** [comment]
I created PRs to move the following pages:

* #40 for [RDF Terminology](https://github.com/w3c/rdf-star-wg/wiki/RDF-Terminology)
* #41 for the [Editor's Guide](https://github.com/w3c/rdf-star-wg/wiki/Editor%27s-guide)
* #42 for [Systems and Acronyms](https://github.com/w3c/rdf-star-wg/wiki/systems-and-acronyms)

Once merged, the wiki entries can be updated to be pointers.

There is already document for [Text Direction](https://github.com/w3c/rdf-star-wg/blob/main/docs/text-direction.md).

The [Scribes](https://github.com/w3c/rdf-star-wg/wiki/Scribes) wiki seems best left as a wiki.

**Comment by TallTed** [comment]
@gkellogg — I have removed the `complete` label, as I don't consider it complete, given my comments above.  I think it's fair for you to un-assign yourself, as the task is larger than originally conceived.  I'd be happy to take it on, if I have sufficient repo permissions to do all that's necessary.

**Comment by gkellogg** [comment]
> I have not been able to find where/how to EDIT the wiki content, which the [Scribes](https://github.com/w3c/rdf-star-wg/wiki/Scribes) page needs...

It could be a matter of repo permissions. When looking a  [Scribes](https://github.com/w3c/rdf-star-wg/wiki/Scribes), I see "Edit" and "New page" buttons; the "edit" button allows the source to be edited. In this case, under the title, I see the following: 

> Adrian Gschwend edited this page 3 hours ago · [4 revisions](https://github.com/w3c/rdf-star-wg/wiki/Scribes/_history)

That link gets you the history of changes to the page. On the history page, you can select revisions to compare using the "Compare revisions" button.

But, since you've asked, I'll create a PR to add Scribes as a document.

**Comment by gkellogg** [comment]
Added #43  for [Scribes](https://github.com/w3c/rdf-star-wg/wiki/Scribes).
