### ISSUE TITLE
1.1 specs should reference 1.2 versions

### ISSUE THREAD

**Issue by gkellogg** [w3c/rdf-star-wg#84]
From https://github.com/w3c/rdf-star-wg/issues/63#issuecomment-1646665902 in #63, the following specs used different short-name schemes, so don't automatically reference the 1.2 versions. Specs that do, such as [RDF Schema 1.1](https://github.com/w3c/rdf-star-wg/issues/63#issuecomment-1646665902) show the Latest Published Version using the general short name scheme ([rdf-schema](http://www.w3.org/TR/rdf-schema/) in this case) do reference the 1.2 versions.

Either the latest published versions of the following specs should be updated, or some similar reference meathod (such as is used for [rdf-mt](https://www.w3.org/TR/rdf-mt/)) should be employed. Note that ReSpec automatically sets Latest published version to include the version number (e.g., "rdf12-concepts") which is either a scheme we want to stick with, or should be overridden to use unversioned naming.

* [ ] https://www.w3.org/TR/rdf11-concepts/ – Latest published version should be https://www.w3.org/TR/rdf-concepts/
* [ ] https://www.w3.org/TR/n-triples/ – Latest published version should be https://www.w3.org/TR/rdf-n-triples/
* [ ] https://www.w3.org/TR/n-quads/ – Latest published version should be https://www.w3.org/TR/rdf-n-quads/
* [ ] https://www.w3.org/TR/rdf11-mt/ – Latest published version should be https://www.w3.org/TR/rdf-semantics/
* [ ] https://www.w3.org/TR/trig/ – Latest published version should be https://www.w3.org/TR/rdf-trig/
* [ ] https://www.w3.org/TR/turtle/ – Latest published version should be https://www.w3.org/TR/rdf-turtle/
* [ ] https://www.w3.org/TR/rdf-syntax-grammar/ – Latest published version should be https://www.w3.org/TR/rdf-xml/
* [ ] https://www.w3.org/TR/sparql11-overview/ – Latest published version should be https://www.w3.org/TR/sparql-concepts/
* [ ] https://www.w3.org/TR/sparql11-update/ – Latest published version should be https://www.w3.org/TR/sparql-update/
* [ ] https://www.w3.org/TR/sparql11-service-descsription/ – Latest published version should be https://www.w3.org/TR/sparql-service-descsription/
* [ ] https://www.w3.org/TR/sparql11-federated-query/ – Latest published version should be https://www.w3.org/TR/sparql-federated-query/
* [ ] https://www.w3.org/TR/sparql11-results-json/ – Latest published version should be https://www.w3.org/TR/sparql-results-json/
* [ ] https://www.w3.org/TR/sparql11-results-csv-tsv/ – Latest published version should be https://www.w3.org/TR/sparql-results-csv-tsv/
* [ ] https://www.w3.org/TR/rdf-sparql-XMLres/ – Latest published version should be https://www.w3.org/TR/sparql-results-xml/
* [ ] https://www.w3.org/TR/sparql11-entailment/ – Latest published version should be https://www.w3.org/TR/sparql-entailment/
* [ ] https://www.w3.org/TR/sparql11-protocol/ – Latest published version should be https://www.w3.org/TR/sparql-protocol/
* [ ] https://www.w3.org/TR/sparql11-http-rdf-update/ – Latest published version should be https://www.w3.org/TR/sparql-graph-store-protocol//

**Comment by pchampin** [comment]
There is an ambiguity in what exactly "Latest Published Version" is supposed to point to: is it
* the latest published release of *this particular version* of the spec, or
* the latest published release of *any version* of the spec

The use of the term "version" points to the 2nd interpretation, but the fact that ReSpec uses the versioned short name points to the first one... I'll git into this.

**Comment by pchampin** [comment]
According to @deniak, the latest published version link should point to the shortlink for *that
same version* as the doc itself, e.g. [css-transitions-2](https://www.w3.org/TR/2023/WD-css-transitions-2-20230905/).

@deniak also points out that certain editors include an additional link to the latest recommendation ([example here](https://www.w3.org/TR/2023/PR-WCAG22-20230720/)), which I believe is in line with what @gkellogg suggested yesterday during the call.

**Comment by pchampin** [comment]
As an aside, I notice that WCAG has chosen a different strategy for version-less names than us: [TR/WCAG](https://www.w3.org/TR/WCAG/) does not point to the most recent document (currently [WCAG 2.2 Proposed Recommendation](https://www.w3.org/TR/2023/PR-WCAG22-20230720/)) but to the most recent *recommendation* ([WCAG 2.1](https://www.w3.org/TR/WCAG21/)).

Maybe that is something we want to consider.

**Comment by pchampin** [comment]
This was discussed during [today's meeting](https://www.w3.org/2023/10/05-rdf-star-minutes.html).

* Last Published Version → same version number
* Versionless short name → latest CR/PR/REC across all version number
